/// Tabella Morse standard (A-Z, 0-9), coi glifi visivi richiesti dalla
/// specifica: "•" per il punto, "⁃" per la linea.
const Map<String, String> morseEncodeTable = {
  'A': '•⁃',
  'B': '⁃•••',
  'C': '⁃•⁃•',
  'D': '⁃••',
  'E': '•',
  'F': '••⁃•',
  'G': '⁃⁃•',
  'H': '••••',
  'I': '••',
  'J': '•⁃⁃⁃',
  'K': '⁃•⁃',
  'L': '•⁃••',
  'M': '⁃⁃',
  'N': '⁃•',
  'O': '⁃⁃⁃',
  'P': '•⁃⁃•',
  'Q': '⁃⁃•⁃',
  'R': '•⁃•',
  'S': '•••',
  'T': '⁃',
  'U': '••⁃',
  'V': '•••⁃',
  'W': '•⁃⁃',
  'X': '⁃••⁃',
  'Y': '⁃•⁃⁃',
  'Z': '⁃⁃••',
  '0': '⁃⁃⁃⁃⁃',
  '1': '•⁃⁃⁃⁃',
  '2': '••⁃⁃⁃',
  '3': '•••⁃⁃',
  '4': '••••⁃',
  '5': '•••••',
  '6': '⁃••••',
  '7': '⁃⁃•••',
  '8': '⁃⁃⁃••',
  '9': '⁃⁃⁃⁃•',
};

final Map<String, String> morseDecodeTable = {
  for (final entry in morseEncodeTable.entries) entry.value: entry.key,
};
